protocols {
    bgp {
        group IBGP-PE {
            type internal;
            local-address {{ router_id }};
            family inet-vpn {
                unicast;
            }
            {% for neighbor in ibgp_neighbors %}
            neighbor {{ neighbor['peer_ip'] }} {
                description "{{ neighbor['description'] }}";
            }
            {% endfor %}
        }
    }
}

routing-options {
    autonomous-system {{ bgp_as }};
    router-id {{ router_id }};
}
