protocols {
    bgp {
        group EBGP-PE {
            type external;
            {% for neighbor in bgp_neighbors %}
            neighbor {{ neighbor['peer_ip'] }} {
                description "{{ neighbor['description'] }}";
                peer-as {{ neighbor['peer_as'] }};
            }
            {% endfor %}
        }
    }
}

routing-options {
    autonomous-system {{ bgp_as }};
    router-id {{ router_id }};
}
