protocols {
    ospf {
        area 0 {
            {% for interface in interfaces %}
            {% if interface['type'] == 'core' %}
            interface {{ interface['if_name'] }};
            {% endif %}
            {% if interface['type'] == 'loopback' %}
            interface {{ interface['if_name'] }} {
                passive;
            }
            {% endif %}
            {% endfor %}
        }
    }
}

routing-options {
    router-id {{ router_id }};
}

security {
    zones {
        security-zone trust {
            host-inbound-traffic {
                protocols {
                    all;
                }
                system-services {
                    all;
                }
            }
            interfaces {
                {% for interface in interfaces %}
                {{ interface['if_name'] }} {
                    host-inbound-traffic {
                        system-services {
                            all;
                        }
                    }
                }
                {% endfor %}
            }
        }
    }
}
