routing-instances {
    {% for vrf in vrfs %}
    {{ vrf['name'] }} {
        instance-type vrf;
        route-distinguisher {{ vrf['rd'] }};
        vrf-target {
            export target:{{ vrf['rt_export'] }};
            import target:{{ vrf['rt_import'] }};
        }
        vrf-table-label;
        {% for iface in vrf['interfaces'] %}
        interface {{ iface }}.0;
        {% endfor %}
        protocols {
            bgp {
                group EBGP-CE {
                    type external;
                    peer-as {{ vrf['ce_neighbor']['peer_as'] }};
                    neighbor {{ vrf['ce_neighbor']['peer_ip'] }};
                }
            }
        }
    }
    {% endfor %}
}
